name: Update analytics

on:
  repository_dispatch:
    types: [update_analytics]

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update analytics data
        run: |
          echo '${{ toJson(github.event.client_payload.data) }}' > _data/analytics.json

      - name: Commit and push changes
        run: |
          git config user.name "Analytics Bot"
          git config user.email "bot@linuxmative"
          git add _data/analytics.json
          git commit -m "Update analytics [skip ci]" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT_ANALYTICS }}
